server:
  port: ${SERVER_PORT}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URI}

spring:
  application:
    name: "auctions-service"