eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URI}

server:
  port: ${GATEWAY_PORT}

spring:
  application:
    name: "gateway-service"

zuul:
  routes:
    ui:
      path: /
      serviceId: "ui-service"

management:
  endpoints:
    web:
      exposure:
        include: "*"