eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${REGISTRY_URI}

server:
  port: 4000

spring:
  application:
    name: "gateway-service"

zuul:
  routes:
    root:
      path: /**
      serviceId: "user-service"

management:
  endpoints:
    web:
      exposure:
        include: "*"