eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://localhost:8000/eureka
      defaultZone: ${REGISTRY_URI}

server:
  port: ${SERVER_PORT}

spring:
  application:
    name: "proposals-service"

management:
  endpoints:
    web:
      exposure:
        include: "*"
