eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      #      defaultZone: http://localhost:8000/eureka
      defaultZone: ${REGISTRY_URI}

server:
  port: 7000

spring:
  application:
    name: "user-api-service"

management:
  endpoints:
    web:
      exposure:
        include: "*"
